language: python
python: 2.7

env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=PyLEMS_NeuroML2
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=jNeuroML_Brain
    - OMV_ENGINE=jNeuroML_validate

install: 
    
    - export main_repo_branch=$TRAVIS_BRANCH
    - echo $main_repo_branch
    - if [[ ${main_repo_branch} != "master" && ${main_repo_branch} != "development" && ${main_repo_branch} != "experimental" ]]; then main_repo_branch=development ; fi
    
    - mvn install
    
    - git clone https://github.com/NeuroML/jNeuroML.git
    - cd jNeuroML
    - git checkout $main_repo_branch
    
    - python getNeuroML.py $main_repo_branch  # will call mvn install on this & other repos
    
    - export PATH=$PATH:$TRAVIS_BUILD_DIR/jNeuroML
    - cd
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
    

script:
    - jnml -v
    - omv all -V
    
